apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cbs6p5s1r-go
  janus-idp.io/tekton: cbs6p5s1r-go
  backstage.io/kubernetes-id: cbs6p5s1r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cbs6p5s1r-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
