apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cbs6p5s1r-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cbs6p5s1r-go 
  name: cbs6p5s1r-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cbs6p5s1r-go 
